#Experiment No 14
# Name: Aanjneya Pankharaj
# Topic: Data Normalization and Data Conversion
# Part-A Data Normalization
## PRN:25070123002
## Batch: ENTC A1

In [5]:
# DataSet
import pandas as pd
import numpy as np
data={
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,50000,40000,5000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15],
    'Discount':[10,15,12,20,18,8]
}
df=pd.DataFrame(data)
print("Original Dataset")
df

Original Dataset

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  50000          60        15
2      Tablet  40000          35        12
3  Headphones   5000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [7]:
#1. Min-Max Normlization
df['Price_MinMax']=(df['Price']-df['Price'].min())/(df['Price'].max()-df['Price'].min())
print("\nMin-Max Normalized Price")
print(df[['Product','Price','Price_MinMax']])

Min-Max Normalized Price
      Product  Price  Price_MinMax
0      Laptop  55000          1.00
1      Mobile  50000          0.90
2      Tablet  40000          0.70
3  Headphones   5000          0.00
4  Smartwatch   8000          0.06
5      Camera  45000          0.80

In [8]:
# Normalization for Units Sold
df['Units_Sold_MinMax']=(df['Units_Sold']-df['Units_Sold'].min())/(df['Units_Sold'].max()-df['Units_Sold'].min())
print("\nMin-Max Normalized Units Sold")
print(df[['Product','Units_Sold','Units_Sold_MinMax']])

Min-Max Normalized Units Sold
      Product  Units_Sold  Units_Sold_MinMax
0      Laptop          25           0.153846
1      Mobile          60           0.692308
2      Tablet          35           0.307692
3  Headphones          80           1.000000
4  Smartwatch          50           0.538462
5      Camera          15           0.000000

In [9]:
# Normalization for Discount
df['Discount_MinMax']=(df['Discount']-df['Discount'].min())/(df['Discount'].max()-df['Discount'].min())
print("\nMin-Max Normalized Discount")
print(df[['Product','Discount','Discount_MinMax']])

Min-Max Normalized Discount
      Product  Discount  Discount_MinMax
0      Laptop        10         0.166667
1      Mobile        15         0.583333
2      Tablet        12         0.333333
3  Headphones        20         1.000000
4  Smartwatch        18         0.833333
5      Camera         8         0.000000

In [10]:
#2 Z-score Normalization
df['Units_Zscore']=(df['Units_Sold']-df['Units_Sold'].mean())/df['Units_Sold'].std()
print("\nZ-score Normalized Units Sold")
print(df[['Product','Units_Sold','Units_Zscore']])

Z-score Normalized Units Sold
      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [12]:
#3. Decimal Scaling
df['Price_Decimal']=df['Price']/100000
print("\nDecimal Scaled Price")
print(df[['Product','Price','Price_Decimal']])

Decimal Scaled Price
      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  50000           0.50
2      Tablet  40000           0.40
3  Headphones   5000           0.05
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [14]:
# Decimal Scaling for Disount
df['Discount_Decimal']=df['Discount']/100
print("\nDecimal Scaled Discount")
print(df[['Product','Discount','Discount_Decimal']])

Decimal Scaled Discount
      Product  Discount  Discount_Decimal
0      Laptop        10              0.10
1      Mobile        15              0.15
2      Tablet        12              0.12
3  Headphones        20              0.20
4  Smartwatch        18              0.18
5      Camera         8              0.08

In [15]:
# Normalize Multiple Coloumns
cols=['Price','Units_Sold','Discount']
df_norm=(df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())
print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
   Price  Units_Sold  Discount
0   1.00    0.153846  0.166667
1   0.90    0.692308  0.583333
2   0.70    0.307692  0.333333
3   0.00    1.000000  1.000000
4   0.06    0.538462  0.833333
5   0.80    0.000000  0.000000

# Part-B Data Conversion

In [16]:
import pandas as pd
import numpy as np
data={
    'Order_ID':[101,102,103,104,105,106],
    'Customer_Gender':['Male','Female','Female','Male','Male','Female'],
    'Payment_Method':['Credit Card','UPI','UPI','Credit Card','Cash','Cash'],
    'Product_Category':['Electronics','Clothing','Electronics','Home','Books','Electronics'],
    'City':['Mumbai','Delhi','Bangalore','Chennai','Kolkata','Pune'],
    'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df=pd.DataFrame(data)
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,Credit Card,Electronics,Mumbai,4500
1,102,Female,UPI,Clothing,Delhi,2300
2,103,Female,UPI,Electronics,Bangalore,3200
3,104,Male,Credit Card,Home,Chennai,5200
4,105,Male,Cash,Books,Kolkata,1800
5,106,Female,Cash,Electronics,Pune,4100

In [20]:
# Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Customer_Gender_Encoded'] = le.fit_transform(df['Customer_Gender'])
print(df)

   Order_ID Customer_Gender Payment_Method Product_Category       City  \
0       101            Male    Credit Card      Electronics     Mumbai
1       102          Female            UPI         Clothing      Delhi
2       103          Female            UPI      Electronics  Bangalore
3       104            Male    Credit Card             Home    Chennai
4       105            Male           Cash            Books    Kolkata
5       106          Female           Cash      Electronics       Pune

   Order_Value  Customer_Gender_Encoded
0         4500                        1
1         2300                        0
2         3200                        0
3         5200                        1
4         1800                        1
5         4100                        0

In [25]:
# Method 2: One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Payment_Method', 'Product_Category', 'City'])
print(df_encoded)

   Order_ID Customer_Gender  Order_Value  Customer_Gender_Encoded  \
0       101            Male         4500                        1
1       102          Female         2300                        0
2       103          Female         3200                        0
3       104            Male         5200                        1
4       105            Male         1800                        1
5       106          Female         4100                        0

   Payment_Method_Cash  Payment_Method_Credit Card  Payment_Method_UPI  \
0                False                        True               False
1                False                       False                True
2                False                       False                True
3                False                        True               False
4                 True                       False               False
5                 True                       False               False

   Product_Category_Books  Product_Category_Clothing  \
0                   False                      False
1                   False                       True
2                   False                      False
3                   False                      False
4                    True                      False
5                   False                      False

   Product_Category_Electronics  Product_Category_Home  City_Bangalore  \
0                          True                  False           False
1                         False                  False           False
2                          True                  False            True
3                         False                   True           False
4                         False                  False           False
5                          True                  False           False

   City_Chennai  City_Delhi  City_Kolkata  City_Mumbai  City_Pune
0         False       False         False         True      False
1         False        True         False        False      False
2         False       False         False        False      False
3          True       False         False        False      False
4         False       False          True        False      False
5         False       False         False        False       True

In [30]:
# Method 3: Encoding Multiple Coloumns
df_multi=pd.get_dummies(df,columns=['Product_Category','City'])
print(df_multi)

   Order_ID Customer_Gender Payment_Method  Order_Value  \
0       101            Male    Credit Card         4500
1       102          Female            UPI         2300
2       103          Female            UPI         3200
3       104            Male    Credit Card         5200
4       105            Male           Cash         1800
5       106          Female           Cash         4100

   Customer_Gender_Encoded  Product_Category_Books  Product_Category_Clothing  \
0                        1                   False                      False
1                        0                   False                       True
2                        0                   False                      False
3                        1                   False                      False
4                        1                    True                      False
5                        0                   False                      False

   Product_Category_Electronics  Product_Category_Home  City_Bangalore  \
0                          True                  False           False
1                         False                  False           False
2                          True                  False            True
3                         False                   True           False
4                         False                  False           False
5                          True                  False           False

   City_Chennai  City_Delhi  City_Kolkata  City_Mumbai  City_Pune
0         False       False         False         True      False
1         False        True         False        False      False
2         False       False         False        False      False
3          True       False         False        False      False
4         False       False          True        False      False
5         False       False         False        False       True

In [29]:
# Method 4: Dummy Encoding (Drop First)
df_dummy=pd.get_dummies(df,columns=['Customer_Gender','Payment_Method','Product_Category','City'],drop_first=True)
print(df_dummy)

   Order_ID  Order_Value  Customer_Gender_Encoded  Customer_Gender_Male  \
0       101         4500                        1                  True
1       102         2300                        0                 False
2       103         3200                        0                 False
3       104         5200                        1                  True
4       105         1800                        1                  True
5       106         4100                        0                 False

   Payment_Method_Credit Card  Payment_Method_UPI  Product_Category_Clothing  \
0                        True               False                      False
1                       False                True                       True
2                       False                True                      False
3                        True               False                      False
4                       False               False                      False
5                       False               False                      False

   Product_Category_Electronics  Product_Category_Home  City_Chennai  \
0                          True                  False         False
1                         False                  False         False
2                          True                  False         False
3                         False                   True          True
4                         False                  False         False
5                          True                  False         False

   City_Delhi  City_Kolkata  City_Mumbai  City_Pune
0       False         False         True      False
1        True         False        False      False
2       False         False        False      False
3       False         False        False      False
4       False          True        False      False
5       False         False        False       True

# New DataSet Operations

In [31]:
# Uploading the DataSet
df=pd.read_csv("/content/amazon_products_dataset_Expt-14.csv")
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [36]:
# Normalize Multiple Coloumns Method 1 Min MAX NORMALIZATION
cols=['Price','Units_Sold','Reviews']
df_norm=(df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())
print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
       Price  Units_Sold   Reviews
0   0.020243    0.518519  0.291005
1   0.048583    0.277778  0.148148
2   0.016194    0.203704  0.119048
3   0.089069    0.629630  0.444444
4   0.149798    0.833333  0.695767
5   0.036437    0.592593  0.351852
6   0.024291    0.129630  0.052910
7   0.064777    0.351852  0.185185
8   0.210526    0.481481  0.378307
9   0.028340    0.222222  0.089947
10  0.311741    1.000000  1.000000
11  0.174089    0.407407  0.444444
12  0.052632    0.500000  0.232804
13  0.016194    0.092593  0.031746
14  0.024291    0.240741  0.119048
15  0.251012    0.444444  0.497354
16  0.036437    0.259259  0.089947
17  0.068826    0.648148  0.312169
18  0.109312    0.851852  0.814815
19  0.040486    0.351852  0.148148
20  0.008097    0.148148  0.000000
21  0.089069    0.444444  0.272487
22  0.352227    0.185185  0.219577
23  0.020243    0.259259  0.079365
24  0.129555    0.592593  0.444444
25  0.174089    0.166667  0.148148
26  0.514170    0.129630  0.708995
27  0.076923    0.370370  0.232804
28  0.016194    0.314815  0.121693
29  0.048583    0.351852  0.150794
30  0.392713    0.240741  0.444444
31  0.230769    0.203704  0.351852
32  0.129555    0.666667  0.550265
33  0.473684    0.092593  0.272487
34  0.635628    0.037037  0.444444
35  0.012146    0.166667  0.007937
36  0.020243    0.462963  0.126984
37  0.000000    0.574074  0.047619
38  0.028340    0.259259  0.079365
39  0.048583    0.111111  0.026455
40  0.109312    0.148148  0.113757
41  0.433198    0.074074  0.206349
42  0.190283    0.351852  0.444444
43  1.000000    0.000000  0.365079
44  0.068826    0.444444  0.259259
45  0.311741    0.240741  0.470899
46  0.757085    0.092593  0.325397
47  0.089069    0.185185  0.148148
48  0.129555    0.148148  0.119048
49  0.028340    0.314815  0.089947

In [39]:
# Normalize Multiple Coloumns Method 2 Z-Score Normalization
df['Units_Zscore']=(df['Units_Sold']-df['Units_Sold'].mean())/df['Units_Sold'].std()
cols=['Price','Units_Zscore','Reviews']
df_norm=(df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())
print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
       Price  Units_Zscore   Reviews
0   0.020243      0.518519  0.291005
1   0.048583      0.277778  0.148148
2   0.016194      0.203704  0.119048
3   0.089069      0.629630  0.444444
4   0.149798      0.833333  0.695767
5   0.036437      0.592593  0.351852
6   0.024291      0.129630  0.052910
7   0.064777      0.351852  0.185185
8   0.210526      0.481481  0.378307
9   0.028340      0.222222  0.089947
10  0.311741      1.000000  1.000000
11  0.174089      0.407407  0.444444
12  0.052632      0.500000  0.232804
13  0.016194      0.092593  0.031746
14  0.024291      0.240741  0.119048
15  0.251012      0.444444  0.497354
16  0.036437      0.259259  0.089947
17  0.068826      0.648148  0.312169
18  0.109312      0.851852  0.814815
19  0.040486      0.351852  0.148148
20  0.008097      0.148148  0.000000
21  0.089069      0.444444  0.272487
22  0.352227      0.185185  0.219577
23  0.020243      0.259259  0.079365
24  0.129555      0.592593  0.444444
25  0.174089      0.166667  0.148148
26  0.514170      0.129630  0.708995
27  0.076923      0.370370  0.232804
28  0.016194      0.314815  0.121693
29  0.048583      0.351852  0.150794
30  0.392713      0.240741  0.444444
31  0.230769      0.203704  0.351852
32  0.129555      0.666667  0.550265
33  0.473684      0.092593  0.272487
34  0.635628      0.037037  0.444444
35  0.012146      0.166667  0.007937
36  0.020243      0.462963  0.126984
37  0.000000      0.574074  0.047619
38  0.028340      0.259259  0.079365
39  0.048583      0.111111  0.026455
40  0.109312      0.148148  0.113757
41  0.433198      0.074074  0.206349
42  0.190283      0.351852  0.444444
43  1.000000      0.000000  0.365079
44  0.068826      0.444444  0.259259
45  0.311741      0.240741  0.470899
46  0.757085      0.092593  0.325397
47  0.089069      0.185185  0.148148
48  0.129555      0.148148  0.119048
49  0.028340      0.314815  0.089947

In [41]:
# Method 3 Decimal Scaling
df['Price_Decimal']=df['Price']/100000
cols=['Price_Decimal','Units_Sold','Reviews']
df_norm=(df[cols]-df[cols].min())/(df[cols].max()-df[cols].min())
print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
    Price_Decimal  Units_Sold   Reviews
0        0.020243    0.518519  0.291005
1        0.048583    0.277778  0.148148
2        0.016194    0.203704  0.119048
3        0.089069    0.629630  0.444444
4        0.149798    0.833333  0.695767
5        0.036437    0.592593  0.351852
6        0.024291    0.129630  0.052910
7        0.064777    0.351852  0.185185
8        0.210526    0.481481  0.378307
9        0.028340    0.222222  0.089947
10       0.311741    1.000000  1.000000
11       0.174089    0.407407  0.444444
12       0.052632    0.500000  0.232804
13       0.016194    0.092593  0.031746
14       0.024291    0.240741  0.119048
15       0.251012    0.444444  0.497354
16       0.036437    0.259259  0.089947
17       0.068826    0.648148  0.312169
18       0.109312    0.851852  0.814815
19       0.040486    0.351852  0.148148
20       0.008097    0.148148  0.000000
21       0.089069    0.444444  0.272487
22       0.352227    0.185185  0.219577
23       0.020243    0.259259  0.079365
24       0.129555    0.592593  0.444444
25       0.174089    0.166667  0.148148
26       0.514170    0.129630  0.708995
27       0.076923    0.370370  0.232804
28       0.016194    0.314815  0.121693
29       0.048583    0.351852  0.150794
30       0.392713    0.240741  0.444444
31       0.230769    0.203704  0.351852
32       0.129555    0.666667  0.550265
33       0.473684    0.092593  0.272487
34       0.635628    0.037037  0.444444
35       0.012146    0.166667  0.007937
36       0.020243    0.462963  0.126984
37       0.000000    0.574074  0.047619
38       0.028340    0.259259  0.079365
39       0.048583    0.111111  0.026455
40       0.109312    0.148148  0.113757
41       0.433198    0.074074  0.206349
42       0.190283    0.351852  0.444444
43       1.000000    0.000000  0.365079
44       0.068826    0.444444  0.259259
45       0.311741    0.240741  0.470899
46       0.757085    0.092593  0.325397
47       0.089069    0.185185  0.148148
48       0.129555    0.148148  0.119048
49       0.028340    0.314815  0.089947

In [45]:
# Uploading the DataSet
df=pd.read_csv("/content/Student-Dataset.csv")
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [46]:
# Method 1: Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Placement_Status_Encoded'] = le.fit_transform(df['Placement_Status'])
print(df)

   Roll_No  Gender  Department  CGPA  Number_of_Backlogs  \
0      101  Female    Computer   8.2                   0
1      102    Male          IT   7.5                   1
2      103  Female        ENTC   9.1                   0
3      104    Male  Mechanical   6.8                   2
4      105  Female    Computer   8.7                   0
5      106    Male       Civil   7.2                   3
6      107  Female          IT   8.9                   0
7      108    Male    Computer   6.5                   1
8      109  Female        ENTC   7.8                   0
9      110    Male  Mechanical   7.0                   2

   Attendance_Percentage Placement_Status  Salary  Placement_Status_Encoded
0                     92           Placed  450000                         1
1                     85       Not Placed       0                         0
2                     96           Placed  550000                         1
3                     78       Not Placed       0                         0
4                     88           Placed  480000                         1
5                     72       Not Placed       0                         0
6                     91           Placed  500000                         1
7                     80       Not Placed       0                         0
8                     84           Placed  420000                         1
9                     76       Not Placed       0                         0

In [47]:
# Method 2: One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Department'])
print(df_encoded)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

  Placement_Status  Salary  Placement_Status_Encoded  Department_Civil  \
0           Placed  450000                         1             False
1       Not Placed       0                         0             False
2           Placed  550000                         1             False
3       Not Placed       0                         0             False
4           Placed  480000                         1             False
5       Not Placed       0                         0              True
6           Placed  500000                         1             False
7       Not Placed       0                         0             False
8           Placed  420000                         1             False
9       Not Placed       0                         0             False

   Department_Computer  Department_ENTC  Department_IT  Department_Mechanical
0                 True            False          False                  False
1                False            False           True                  False
2                False             True          False                  False
3                False            False          False                   True
4                 True            False          False                  False
5                False            False          False                  False
6                False            False           True                  False
7                 True            False          False                  False
8                False             True          False                  False
9                False            False          False                   True

In [48]:
# Method 3: Encoding Multiple Coloumns
df_multi=pd.get_dummies(df,columns=['Department','Placement_Status'])
print(df_multi)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  Salary  \
0      101  Female   8.2                   0                     92  450000
1      102    Male   7.5                   1                     85       0
2      103  Female   9.1                   0                     96  550000
3      104    Male   6.8                   2                     78       0
4      105  Female   8.7                   0                     88  480000
5      106    Male   7.2                   3                     72       0
6      107  Female   8.9                   0                     91  500000
7      108    Male   6.5                   1                     80       0
8      109  Female   7.8                   0                     84  420000
9      110    Male   7.0                   2                     76       0

   Placement_Status_Encoded  Department_Civil  Department_Computer  \
0                         1             False                 True
1                         0             False                False
2                         1             False                False
3                         0             False                False
4                         1             False                 True
5                         0              True                False
6                         1             False                False
7                         0             False                 True
8                         1             False                False
9                         0             False                False

   Department_ENTC  Department_IT  Department_Mechanical  \
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True

   Placement_Status_Not Placed  Placement_Status_Placed
0                        False                     True
1                         True                    False
2                        False                     True
3                         True                    False
4                        False                     True
5                         True                    False
6                        False                     True
7                         True                    False
8                        False                     True
9                         True                    False

In [49]:
# Method 4: Dummy Encoding (Drop First)
df_dummy=pd.get_dummies(df,columns=['Department','Placement_Status'],drop_first=True)
print(df_dummy)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  Salary  \
0      101  Female   8.2                   0                     92  450000
1      102    Male   7.5                   1                     85       0
2      103  Female   9.1                   0                     96  550000
3      104    Male   6.8                   2                     78       0
4      105  Female   8.7                   0                     88  480000
5      106    Male   7.2                   3                     72       0
6      107  Female   8.9                   0                     91  500000
7      108    Male   6.5                   1                     80       0
8      109  Female   7.8                   0                     84  420000
9      110    Male   7.0                   2                     76       0

   Placement_Status_Encoded  Department_Computer  Department_ENTC  \
0                         1                 True            False
1                         0                False            False
2                         1                False             True
3                         0                False            False
4                         1                 True            False
5                         0                False            False
6                         1                False            False
7                         0                 True            False
8                         1                False             True
9                         0                False            False

   Department_IT  Department_Mechanical  Placement_Status_Placed
0          False                  False                     True
1           True                  False                    False
2          False                  False                     True
3          False                   True                    False
4          False                  False                     True
5          False                  False                    False
6           True                  False                     True
7          False                  False                    False
8          False                  False                     True
9          False                   True                    False